### ISSUE TITLE
Who can solve this 403 error?

### ISSUE THREAD

**Issue by oleksandr010419** [cemmydev/django-ledger#30]
I get this error during connecting external API to this project.
I tried to resolve it but still not find it

**Comment by cemmydev** [comment]
try it by forwarding to another port
It can be help for resolving it

**Comment by cemmydev** [comment]
use your vscode

**Comment by oleksandr010419** [comment]
Thanks

**Comment by oleksandr010419** [comment]
> use your vscode

greate
